<?php
 if(Mage::getStoreConfig('zipcodeck/general/enabled') == 1 ){
 ?>
<div class="zipcode-box">
		<div id="zipcode-feed" class="zipcode_cont1">
		<!-- <span><?php echo $this->__('Check Zipcode'); ?></span> -->
			<div class="zipcode_cont2 input-group">
			<input type="text" class='form-control form-cep input-lg' autofocus='autofocus' name="zipcode" id="zipcode" onFocus="resetZipcode(this)" onkeypress="keyEventhandle(event,this.value);"  onBlur="resetZipcode(this)" value="<?php echo $this->__('Enter Zipcode') ?>"  /> 
			 <span class='input-group-btn btn-group-lg'>
				<button onclick="verifyzipcode(document.getElementById('zipcode').value);" class="btn btn-success btn-lg btn-go" title="<?php echo $this->__('Check Zip Code'); ?>" type="button"> <i class='icon-angle-right'></i>
				<!-- <span><?php echo $this->__('Check'); ?></span> --></button>
			</span>
		</div>
		<div id="zipcode-loader" style="display:none;"><img src="<?php echo Mage::getDesign()->getSkinUrl('images/ajax-loader.gif');?>" /></div>
		<span class="validation-advice" id="message-field" style="display:none;"><?php echo $this->__('Por favor, entre com um CEP válido.') ?></span>
	</div>
					
	<div id="zipcode-output" style="display:none;" class="zipcode_cont1">
		<div class="zipcode-option">
			<div class="zipcode-label"> <?php echo $this->__('CEP escolhido: ');?>
			<span class="zipcode_display" id="zipcode_text"></span> 
			 <p><a onclick="setZipcodeBox()" href="javascript:void(0)"><?php echo $this->__('Trocar ');?></a></p>
			</div>
			<div style="display:none;" id="zipcode-invalid">

					<aside id='jack-not-available'>
        <figure>
          <img alt='Delivery' src='assets/images/icn-delivery.svg'>
        </figure>
        
        
     

				<h2 class=""><?php echo $this->__('Ainda não entregamos no seu endereço.');?></h2>

				<a class='btn btn-default btn-md' href='http://52.21.137.15/index.php/monte-seu-pedido.html' id='btn-continue' title='Faça agora o seu pedido'>Continuar e retirar no Jack Salada</a>
				<a class='btn btn-default btn-md' href='http://52.21.137.15/index.php/saladas.html' id='btn-continue' title='Faça agora o seu pedido'>Ver cardápio</a>
				 </aside>
			</div>
			<div id="valid_zipcode" style="display:none;">
			<?php echo $this->__('Ok, entregamos na sua região!');?>
			</div>
			<div id="delevery-city"  style="display:none;"><?php echo $this->__('City: ');?><span id="d-city"></span></div>
			<div id="delevery-days"  style="display:none;"><?php echo $this->__('Delivery Days: ');?><span id="d-days"></span></div>
			<div id="delevery-cod"  style="display:none;"><?php echo $this->__('Cash On Delivery : ');?><span id="d-cod"></span></div>
		</div>            
	</div>
</div>

<script type="text/javascript">  
	function keyEventhandle(e,val)
	{
		if(e.keyCode === 13){
		    verifyzipcode(val);
		    e.preventDefault();
		     return false;
		}               
	}
 
    function verifyzipcode(data)
    {
    	data=data.trim();
		if(typeof data != 'undefined' && data!='' && data!='Enter Zipcode')
		{
			jQuery('#zipcode-loader').show();
			document.getElementById("message-field").style.display = 'none';
			
			new Ajax.Request('<?php echo Mage::getBaseUrl().'zipcodeck/onepage/checkcode';?>', {
			method:'post',
			parameters: {zipcode: data},
			onSuccess: function(transport) {
				var response = transport.responseText || "no response text";
				result = JSON.parse(response);
				if(result.valid=='1')
			      {                     
					jQuery(location).attr('href', 'http://52.21.137.15/index.php/monte-seu-pedido.html');        
					// jQuery( "#zipcode-output").fadeIn();
					// jQuery( "#zipcode-invalid").hide();
					// jQuery( "#valid_zipcode").show();
					// jQuery("#zipcode_text").text(data);
					// jQuery('#zipcode-loader').hide();
					
					if(result.city !=''){
						jQuery( "#delevery-city").show();
						jQuery('#d-city').text(result.city);
					}
					
					if(result.Delivery_Days != 0){
						jQuery( "#delevery-days").show();
						jQuery('#d-days').text(result.Delivery_Days);
					}
					
					if(result.cod !=''){
						jQuery( "#delevery-cod").show();
						jQuery('#d-cod').text(result.cod);
					}
					
			      }else
			      {
					setErrorZipcode();jQuery("#zipcode_text").text(data);
			      }
			},
			onFailure: function() { setErrorZipcode();jQuery("#zipcode_text").text(data); }
			});
		} else	
		 jQuery( "#message-field").fadeIn();
    }
    
	function setErrorZipcode()
	{
		jQuery( "#zipcode-output").fadeIn();
		jQuery( "#zipcode-invalid").fadeIn();
		jQuery( "#zipcode-feed").hide(); 
		jQuery( "#valid_zipcode").hide();
		jQuery( "#delevery-days").hide();
		jQuery( "#delevery-city").hide();
		jQuery( "#delevery-cod").hide();
	}
   
	function setZipcodeBox()
	{
		jQuery('#zipcode-loader').hide();
		jQuery( "#zipcode-feed").fadeIn();
		jQuery( "#valid_zipcode").hide();
		jQuery( "#delevery-days").hide();
		jQuery( "#delevery-city").hide();
		jQuery( "#delevery-cod").hide();
		jQuery( "#zipcode-output").hide();  
		jQuery("#ddays").text('');
	}
    
	function resetZipcode(field){ 
	    if (field.defaultValue == field.value) field.value = '';
	    else if (field.value == '') field.value = field.defaultValue; 
	} 
</script>
        
<?php } ?>